GRANT CREATE MINING MODEL TO c##comm_user;
GRANT SELECT ANY MINING MODEL TO c##comm_user;
GRANT ALTER ANY MINING MODEL TO c##comm_user;
GRANT DROP ANY MINING MODEL TO c##comm_user;
GRANT COMMENT ANY MINING MODEL TO c##comm_user;
