
DROP TABLE Customer_Revenue_Profile_Report;

  CREATE TABLE "C##COMM_USER"."CUSTOMER_REVENUE_PROFILE_REPORT" 
   (	"CUSTOMER_PHONE" VARCHAR2(26 BYTE) NOT NULL ENABLE, 
	"January" NUMBER(20,2), 
	"February" NUMBER(20,2), 
	"March" NUMBER(20,2), 
	"April" NUMBER(20,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;