/* Ciaran Finnegan 	: Student No. D21124026										*/
/* TUD - Class TU060 - MSc In Science (Data Science) - Part Time - First Year 	*/


/* Data Warehouse Design and Implementation : Working With Data - Assignment Two - January 2022			*/

/* -- Set SQL Session to try and pick up EURO Currency symbols   */
alter session set NLS_ISO_CURRENCY='IRELAND';
alter session set NLS_DUAL_CURRENCY = '€';

/* --- SQL REPORT Four  : Revenue Pattersn of Top 20 APRIL Customers --- */

DROP TABLE Customer_Revenue_Profile;
DROP TABLE Customer_Revenue_Profile_Report;


/*---           Add Title to SQL REPORT FOUR Ouptut                    ---*/
TTITLE LEFT 'SQL REPORT FOUR - YTD Revenue Patterns of Top 20 APRIL Customers' SKIP 1 


/*--- Set up a temporary table to capture the data warehouse customer ---*/
/*--- revenue pattersn for the last four months (the complete data range) ---*/
CREATE TABLE Customer_Revenue_Profile AS
  
    /*-- Focus on Top 20 customers in April and extract full YTD breakdown --*/
    SELECT      a.phone_number as Customer_Phone, 
                SUM(c.call_event_charge) as Monthly_Revenue,
                b.Month_of_Year_Num as Month_Number
                
    /*--- Query on Data Warehouse tables ---*/ 
    FROM        dw_dimtblCustomer a,
                dw_dimtblDateTime b,
                dw_facttblCallRevenue c
                    
    WHERE       a.customerphonekey  = c.Customer_Key
    AND         b.datetimekey       = c.datetimekey
    AND         b.Month_of_Year_Num in (1,2,3,4) /*-- All YTD data ---*/
    AND         a.phone_number      IN
                (
                /*--- Select Customer Phone Numbers based on Sum of Charges in April--- */
                SELECT Cust_Number
                
                FROM
                (
                    /*--- Sub query SUMS the charge amounts in FACT Table --- */
                    SELECT      d.phone_number as Cust_Number, 
                                SUM(f.call_event_charge) as Total_Revenue_April                                     
                 
                    FROM        dw_dimtblCustomer d,
                                dw_dimtblDateTime e,
                                dw_facttblCallRevenue f
                                
                    WHERE       d.customerphonekey  = f.Customer_Key
                    AND         e.datetimekey       = f.datetimekey
                    AND         e.Month_of_Year_Num in (4) /*-- Last Month (April) ---*/
                 
                    GROUP BY    d.phone_number
                
                )
                /*--- Order query to show Top 20 customers by customer charge ---*/
                ORDER BY Total_Revenue_April DESC
                fetch first 20 row only
                )
    GROUP BY a.phone_number, b.Month_of_Year_Num
    ORDER BY a.phone_number DESC, b.Month_of_Year_Num ASC;            



/*-- Use temp table for report presentation --*/
CREATE TABLE Customer_Revenue_Profile_Report AS

    /*--- Invert Columns/Rows from Customer Revenue Query ---*/ 
    /*--- This generates month by month report view  ---*/ 
    select * from Customer_Revenue_Profile 
    PIVOT (
        sum(MONTHLY_REVENUE) for 
                Month_Number in (1 "January",2 "February",3 "March",4 "April")
        )
    order by CUSTOMER_PHONE; 



/*--- Add a column to the report table to capture the YTD revenue  ---*/
/*--- generated by the top 20 April customers                      ---*/
ALTER TABLE
    Customer_Revenue_Profile_Report
ADD
    YTD_Revenue	NUMBER(20,2);
  

/*-- Calculate the YTD revenue for each of the TOP 20 April csutomers  --*/    
UPDATE Customer_Revenue_Profile_Report
SET YTD_Revenue = (Customer_Revenue_Profile_Report."January"
                   + Customer_Revenue_Profile_Report."February"
                   + Customer_Revenue_Profile_Report."March"
                   + Customer_Revenue_Profile_Report."April");



/*---  Display the YTD Revenue Report for Top 20 April Customers  ---*/
SET sqlformat ansiconsole;
/*---           Format Column Output of Report for Presentation       ---*/

COLUMN CUSTOMER_PHONE             FORMAT A13 HEADING 'Customer|Phone Number' 
COLUMN January                    FORMAT A13 HEADING 'January|Revenue (€)' 
COLUMN February                   FORMAT A13 HEADING 'February|Revenue (€)' 
COLUMN March                      FORMAT A13 HEADING 'March|Revenue (€)' 
COLUMN April                      FORMAT A13 HEADING 'April|Revenue (€)' 
COLUMN YTD_REVENUE                FORMAT A13 HEADING 'YTD|Revenue(€)' 

SELECT * FROM Customer_Revenue_Profile_Report
ORDER BY ytd_revenue DESC; /*---  Highest Revenue Customers First   ---*/

